config/routes.rb
ShareChart::Application.routes.draw do

  root                  :to => 'pages#home'
  match '/chart',       :to => 'pages#chart'
  match '/makeindex',   :to => 'companies#make_index'
  
  get 'indices/add_company_to_index'
  get 'indices/remove_company_from_index'
  
  get 'companies/get_company_record_data'
  get 'indices/get_index_record_data'
  
  resources :indices
  resources :companies
  resources :records
  resources :date_ranges

end

app/models/company.rb
# == Schema Information
# Schema version: 20110513080243
#
# Table name: companies
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  description  :string(255)
#  industry     :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  abbreviation :string(255)
#

class Company < ActiveRecord::Base
  attr_accessible :name, :description, :industry, :abbreviation

  has_many :records
  has_and_belongs_to_many :indices
  
  validates :name,         :presence => true
  validates :abbreviation, :presence => true,
                           :length => { :within => 3..10 },
                           :uniqueness => { :case_sensitive => false }
end

app/controllers/companies_controller.rb
require 'net/http'
require 'uri'

class CompaniesController < ApplicationController
  def new
    @title = "Add new company"
    @company = Company.new
  end

  def create
    @title = "Add new company"
    @company = Company.new(params[:company])
    @company.abbreviation = @company.abbreviation.upcase
    
    start_year = "2010"
    start_month = "00"
    start_day = "1"
    end_year = Time.now.year.to_s
    end_month = (Time.now.month - 1) < 10 ? 
          "0#{(Time.now.month - 1).to_s}" : (Time.now.month - 1).to_s
    end_day = Time.now.day.to_s
    csv_file = "http://ichart.finance.yahoo.com/table.csv?" + 
      "s=#{@company.abbreviation}&a=#{start_month}&b=#{start_day}" +
      "&c=#{start_year}&d=#{end_month}&e=#{end_day}&f=#{end_year}" + 
      "&g=d&ignore=.csv"
    
    csv_string = Net::HTTP.get URI.parse(csv_file)
    
    if csv_string.first == "<"
      flash[:error] = "Error retrieving data for #{params[:company][:abbreviation].upcase}"
    else
      if @company.save
        
        lines = csv_string.split("\n")
        lines = lines.drop(1)
        lines.each do |line|
          atts = line.split(",")
          Record.create(:time => atts[0],
                        :open => atts[1],
                        :high => atts[2],
                        :low => atts[3],
                        :close => atts[4],
                        :volume => atts[5],
                        :adjClose => atts[6],
                        :company_id => @company.id)
        end
        flash[:success] = "#{params[:company][:name]} added to database"
      else
        flash[:error] = "Error adding #{params[:company][:name]} to database"
      end
    end
    redirect_to @company
  end
  
  def index
    @title = "Companies"
    @companies = Company.all(:conditions => "abbreviation != '.INDEX'")
  end

  def show
    @company = Company.find(params[:id])
    @title = "#{@company.name} (#{@company.abbreviation})"
    @new_record = Record.new(:time => 7.hours.ago(Time.now.midnight))
    @date_range = DateRange.new
    @records = @company.records.paginate(:page => params[:page])
  end

  def edit
  end

  def destroy
    Company.find(params[:id]).destroy
    flash[:success] = "Company removed"
    redirect_to companies_path
  end
  
  def get_company_record_data
    @company = Company.find_by_abbreviation(params[:q])
    @records = @company.records.all
    render :layout => false
  end
  
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/views/companies/destroy.html.erb
<h1>Companys#destroy</h1>
<p>Find me in app/views/companys/destroy.html.erb</p>

app/views/companies/edit.html.erb
<h1>Companys#edit</h1>
<p>Find me in app/views/companys/edit.html.erb</p>

app/views/companies/get_company_record_data.html.erb
<% @records.each do |record| %>
  <%= "#{record.time.year}-#{record.time.month}-#{record.time.day},#{record.open},#{record.high},#{record.low},#{record.close}" %>
<% end %>

app/views/companies/index.html.erb
<div id="add_company_button"><%= link_to "Add new company", new_company_path, :class => "button round" %></div>

<table>
  <tr>
    <th>Name</th>
    <th>Abbrev</th>
    <th>Industry</th>
    <th>Description</th>
  </tr>
  <% @companies.each do |company| %>
    <tr>
      <td><%= link_to company.name, company %></td>
      <td><%= company.abbreviation %></td>
      <td><%= company.industry %></td>
      <td><%= company.description %></td>
      <td><%= link_to "delete", company, :method => :delete, :confirm => "Are you sure?" %></td>
    </tr>
  <% end %>
</table>

app/views/companies/make_index.html.erb
<p>AAAaaaarrrrgggg</p>

app/views/companies/new.html.erb
<%= form_for(@company) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/companies/show.html.erb
<% session[:company_id] = @company.id %>
<section class="record_form round">
  <h3>Add single record</h3>
  <%= form_for(@new_record) do |f| %>
    <ul class="form_list">
      <li><%= f.label :time %><br />
          <%= f.datetime_select :time %></li>
      <li>
        <ul>
          <li class="number_field"><%= f.label :open %><br />
              <%= f.number_field :open, :size => 4 %></li>
          <li class="number_field"><%= f.label :high %><br />
              <%= f.number_field :high, :size => 4 %></li>
          <li class="number_field"><%= f.label :low %><br />
              <%= f.number_field :low, :size => 4 %></li>
          <li class="number_field"><%= f.label :close %><br />
              <%= f.number_field :close, :size => 4 %></li>
          <li class="number_field"><%= f.label :volume %><br />
              <%= f.number_field :volume, :size => 8 %></li>
        </ul>
      </li>
    </ul>
    <div class="actions">
      <%= f.submit "Add" %>
    </div>
  <% end %>
</section>
<section class="record_form round">
  <h3>Download records</h3>
  <%= form_for(@date_range) do |f| %>
    <ul class="form_list">
      <li><%= f.label "Start date" %><br />
          <%= f.date_select :start_date %></li>
      <li><%= f.label "End date" %><br />
          <%= f.date_select :end_date %></li>
    </ul>
    <div class="actions">
      <%= f.submit "Download" %>
    </div>
  <% end %>
</section>
<section>
  <h2>Historical Data from Yahoo Finance</h2>
  <table class="records" summary="Company records">
    <tr>
      <th>Time</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Volume</th>
    </tr>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.time %></td>
        <td><%= record.open %></td>
        <td><%= record.high %></td>
        <td><%= record.low %></td>
        <td><%= record.close %></td>
        <td><%= record.volume %></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @records %>
</section>