config/routes.rb
ShareChart::Application.routes.draw do

  root                  :to => 'pages#home'
  match '/chart',       :to => 'pages#chart'
  match '/makeindex',   :to => 'companies#make_index'
  
  get 'indices/add_company_to_index'
  get 'indices/remove_company_from_index'
  
  get 'companies/get_company_record_data'
  get 'indices/get_index_record_data'
  
  resources :indices
  resources :companies
  resources :records
  resources :date_ranges

end

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag :defaults %>
<%= javascript_include_tag 'amcharts/javascript/amcharts.js' %>
<%= javascript_include_tag 'amcharts/javascript/raphael.js' %>      

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'style', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title id="title">Shart | <%= @title %></title>
    <%= render 'layouts/stylesheets' %>
    <%= render 'layouts/javascripts' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <header class="container round">
      <div class="title">
        <h1 id="heading"><%= @title %></h1>
      </div>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path, :class => "button round" %></li>
          <li><%= link_to "Chart", chart_path, :class => "button round" %></li>
          <li><%= link_to "Indices", indices_path, :class => "button round" %></li>
          <li><%= link_to "Companies", companies_path, :class => "button round" %></li>
        </ul>
      </nav>
    </header>
    <section class="container round">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </section>
  </body>
</html>